#include <stdio.h>
#include <stdlib.h>
#include "gba.h"
#include "game.h"

#include <string.h>
                    /* TODO: */
// Include any header files for title screen or exit
// screen images generated by nin10kit. Example for the provided garbage
// image:
#include "images/garbage.h"
#include "images/welcome.h"
#include "images/pond.h"
#include "images/snake.h"
#include "images/water.h"
#include "images/gun.h"
#include "images/play.h"
#include "images/win.h"
#include "images/rules.h"


                    /* TODO: */
// Add any additional states you need for your app.
typedef enum {
    START,
    PLAY,
    RULES,
    WIN,
} GBAState;

Orb red = {10,10,10,10,0};
Orb blue = {220,83,10,10,0};

int main(void) {
                    /* TODO: */
    // Manipulate REG_DISPCNT here to set Mode 3. // Done
    REG_DISPCNT = MODE3 | BG2_ENABLE;


    // Save current and previous state of button input.
    // unsigned short buttons;
    // unsigned short oldButtons;
    u32 previousButtons = BUTTONS;
    u32 currentButtons = BUTTONS;

    // Load initial game state
    GBAState state = START;


    while (1) {
        waitForVBlank();
        currentButtons = BUTTONS; // Load the current state of the buttons


                    /* TODO: */
        // Manipulate the state machine below as needed //
        // NOTE: Call waitForVBlank() before you draw

        switch(state) {
            case START:

                drawFullScreenImageDMA(welcome);

                    // waitForVBlank();

                    drawString(0, 125, "'START' to start 'A' for rules", RED);
                    if (KEY_PRESSED(BUTTON_START)) {
                    state = PLAY;
                    }

                    if (KEY_PRESSED(BUTTON_A)) {
                    state = RULES;
                    }

                break;

            case PLAY:
                // waitForVBlank();

                drawFullScreenImageDMA(play);

                drawRectDMA(red.y,red.x,red.h,red.w,RED);
                // drawRectDMA(37,33,1,1,GREEN);
                // drawRectDMA(63,73,1,1,GREEN);


                // drawRectDMA(63,123,1,1,GREEN);
                // drawRectDMA(63,97,1,1,GREEN);

                // drawRectDMA(63,154,1,1,GREEN);
                // drawRectDMA(63,188,1,1,GREEN);
                // waitForVBlank();
                drawRectDMA(blue.y,blue.x,blue.h,blue.w,BLUE);

                drawString(0, 135, "-> possess snake, water, or gun", RED);

                // drawRectDMA(10,220,10,10,BLUE);
                if (red.status == 0) {
                    if (KEY_PRESSED(BUTTON_DOWN)) {red.y++; }
                    if (KEY_PRESSED(BUTTON_UP)) { red.y--;  }
                    if (KEY_PRESSED(BUTTON_LEFT)) { red.x--;}
                    if (KEY_PRESSED(BUTTON_RIGHT)) { red.x++;}

                    if (red.x > 37 && red.x < 63 && red.y > 33 && red.y < 65) {
                        red.status = 1;
                    }

                    if (red.x > 97 && red.x < 123 && red.y > 33 && red.y < 65) {
                        red.status = 2;
                    }

                    if (red.x > 154 && red.x < 188 && red.y > 33 && red.y < 65) {
                        red.status = 3;
                    }

                } else {
                    if (red.status != 2) {
                        blue.status = (red.status + 1) % 3;
                    } else {
                        blue.status = 3;
                    }
                    state = WIN;

                }


                if (KEY_PRESSED(BUTTON_SELECT)) {
                     state = START;
                    red.x = 10;
                    red.y = 10;
                    red.status = 0;
                }
                break;

            case WIN:
                drawRectDMA(0, 0, 240,160,GREEN);

                drawImageDMA(10, 20, 80, 30, win);

                if (red.status == 1) {
                    drawString(10, 100, "Your snake beats water", RED);
                } else if (red.status == 2) {
                    drawString(10, 100, "Your water beats gun", RED);
                } else {
                    drawString(10, 100, "Your gun beats snake", RED);
                }




                if (KEY_PRESSED(BUTTON_SELECT)) {
                    state = START;
                    red.x = 10;
                    red.y = 10;
                    red.status = 0;
                }
                break;
            case RULES:

                drawImageDMA(0,0,240,160, rules);
                if (KEY_PRESSED(BUTTON_SELECT)) {
                    state = START;
                    red.x = 10;
                    red.y = 10;
                    red.status = 0;
                }
            break;
        }



        previousButtons = currentButtons; // Store the current state of the buttons
    }

    UNUSED(previousButtons); // You can remove this once previousButtons is used

    return 0;
}
